### ISSUE TITLE
Array index is out of bounds on certain records (Route.java:313)

### ISSUE THREAD

**Issue by zppratt** [zppratt/EMS#1]
Stack trace:

java.lang.ArrayIndexOutOfBoundsException: 0
    at com.baconfiesta.ems.models.EmergencyRecord.Route.calculateDirections(Route.java:313)
    at com.baconfiesta.ems.models.EmergencyRecord.Route.<init>(Route.java:45)
    at com.baconfiesta.ems.view.EMSInterface.lambda$manageRecords$20(EMSInterface.java:1567)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)

Steps to reproduce:
-Manage records
-Change name of caller
-Press "save"

My theory is that some locations can't be fetched for a route somehow.

**Comment by zppratt** [comment]
Note: This only happens on some records

**Comment by SunnyDjinn** [comment]
Added exceptions handling. Resolved
